### ISSUE TITLE
Museum detail page - early scroll transition

### ISSUE THREAD

**Issue by jbranigan** [azavea/imls-museum-data#50]
When scrolling down, the transition from museum detail / analysis tools to header happens about 400px early.

**Comment by designmatty** [comment]
So here's what I was able to figure out.

The JS that is controlling the affix is being fired before the dom is finished rendering. 

Because of this, it's not waiting to calculate the action-bar's true position on the screen. This would be easy for me to fix if the browser were actually reloading. Since I'm not familiar enough with angular I might defer to @CloudNiner or @sharph and have them trigger some sort of watch function.

**Comment by designmatty** [comment]
Whoever would like to take the lead on this, let me know. I'll sit down with you and show you exactly what I was able to figure out, which might help you decide on how to fix this.

**Comment by designmatty** [comment]
I was ultimately able to fix this by wrapping the script in a timeout function. fixed in #62
