### ISSUE TITLE
First Round of Design/UX/Functionality Feedback

### ISSUE THREAD

**Issue by nevillevak** [azavea/imls-museum-data#59]
Hello - Based on our first look at the tool, below is our list of feedback. I'll also email a Word doc since I can't attach it here.

I will also be providing the initial content blocks for the static pages.

John - let me know if you'd like to talk through these items.
---------------

MuseumStat: Design and Functionality Feedback, Round 1
September 4, 2015

Design:

•	MuseumStat logo in upper left should be larger and clearer; tagline is very hard to read (we can provide the correct file format/resolution of the logo – please specify)

•	Make IMLS and Drexel logos larger; the correct Westphal logo will be provided

•	The large open space under the map is prime space that could be either reduced or used to provide useful content. It also looks like it is a link to a search function because of what’s written there. Making the default text in the search bar state “Search by Museum, Address, City, or Zip” instead of just “Search” – then there is no need for the box below the map. This could instead have a larger MuseumStat logo and brief descriptive text (to be determined)

•	Legend and map point colors – use some brighter colors that provide more contrast from each other (possibly only a few new colors will make it clearer)

•	Add an additional navigation item at the top labeled “Help” as we will use that page to include basic instructions, examples, etc. Our user base will need this type of support (initial content will be provided). Consider removing the “Home” link at the top since the logo should always link back to home.

•	Phone numbers in the museum detail page display as a long string; format as standard 10-digit US phone numbers.

•	Remove “Powered by CartoDB” if at all possible.

Functionality/UX:

•	If user searches for and selects a specific museum from the list in the search bar, it can be confusing on the next screen, since it typically shows a large number in the “## Results Found” list.  It would be better to show the single, selected result, with some demarcation below showing that the rest of the lists are museums in the area. This should be a clearer way to show this. Alternately, should selecting a specific museum take the user directly to the detail page for museum? 

•	The “Address” column in the results page does not display anything. Alternately, could this column be used for URL? 

•	The “Type” column uses the abbreviations; is it possible to use the legend name? Otherwise, the user has no indication of what the initials mean. Alternately, these initials can be parenthetically added to the end of each legend name.

•	For “Revenue” column, if there is no value, is it worthwhile to put “na” or similar? Or is blank preferred?

•	The “View” button may be better named as “View & Analyze” or “Analyze” so it’s clear that that where the user can go deeper into analysis. Or Perhaps there’s a better single word.

•	When selecting a museum, the “Families in Poverty” chloropleth automatically appears. The screen should start with no chloropleth layers active and the user can select layers to start with.

•	When a museum is selected, the pin icon should remain so that the user always knows where the museum is and which museum is selected. The pin goes away when going from the search results page to the museum detail page.

•	The results page information does not change when the map is zoomed in or out.

•	The layers icon, could be more prominent; perhaps including the word “Layers” next to the graphic would help the user know what it is (again, the user base for this tool is not savvy with mapping-related tools).

•	When scrolling down on a museum detail page (on 13” MacBook Air) there is a large whitespace between the bottom of the map and the visual display of data. See screen cap below:

•	“Submit Museum Update” – page content and form fields will be provided.

•	Make the custom radius show miles as it is being drawn, rather than km.

•	In general, it is vital that there be an easy way for users to see % in addition to (or in same cases, instead of) the full value. In some cases, this can be added to the roll-over box that displays the number. In some cases, this would be best if it were added to the chart (such as with the bar charts for Race and Employment). In most cases, users are more interested in % than actual numbers, so graphs could display % and show the actual number in the roll-over.

•	We need to include some basic measure of Hispanic/Latino population, which is not currently on this; it could be a component of the Race chart (relabled as “Race/Ethnicity”) or as a single number/percent.

•	The “NEARBY MUSEUMS” label is still being reviewed in terms of an ideal name. Will review and determine if there is an alternate label selected.

•	In the “NEARBY MUSEUMS” charts, the total number should be provided in the heading, such as “Museums in State: ####” as the header. Same applies to “Museums in Selected Area.”

•	Switch the order of “Museums in Selected Area” and “Museums in State” to display the specific area first, then to the broader geography.

•	In the “Households” tab, the first three data boxes should be Total Households, Median Household Income, Median Home Value (in that order). The next three should be Median Year Moved In, Household Types, Household Languages

•	In general, the labels for the data in all three tabs should be consistently written, using a capital letter for the first letter of each word (except for ancillary words like of, in, etc.

•	In “NEARBY MUSEUMS” – We will be providing information on an additional chart and measures that would appear in this section. 

•	In the footer of the data pages, include the sources, in small text:
“People and Household Data: U.S. Census Bureau, American Community Survey, 2009-2013.”
“Museum Data: Museum Universe Data File, Compiled by IMLS and Drexel University.”

•	Change the radius drop down options to 1, 3, and 25 miles to accommodate rural areas.

•	CMS: How will we be able to update the static content on pages such as “About,” “Contact,” “Help,” etc? Is it a WordPress template?

•	Is it preferable for the contact mechanism to be a contact form vs. email address? If a form is best, a standard form with contact info and comment box should suffice. The form can transmit to nvakharia@drexel.edu, with a subject line of “MuseumStat Contact”

(Note: “3D STREET GALLERY” shows up on a map result in Philadelphia, but has a listed address of Grand Forks, ND – please look into the cause of this)

Future Work (short-term):

•	In the “Layers” function, allow users to select by museum type.

•	Ability to select an entire state and see the analysis.

•	Simple ability to share a map and data page.

•	Additional point and layer data to include public schools, congressional districts, etc.

**Comment by jbranigan** [comment]
Design:

- [ ] MuseumStat logo in upper left should be larger and clearer; tagline is very hard to read (we can provide the correct file format/resolution of the logo – please specify)

- [ ] Make IMLS and Drexel logos larger; the correct Westphal logo will be provided

- [ ] The large open space under the map is prime space that could be either reduced or used to provide useful content. It also looks like it is a link to a search function because of what’s written there. Making the default text in the search bar state “Search by Museum, Address, City, or Zip” instead of just “Search” – then there is no need for the box below the map. This could instead have a larger MuseumStat logo and brief descriptive text (to be determined)

- [x] Legend and map point colors – use some brighter colors that provide more contrast from each other (possibly only a few new colors will make it clearer)

- [x] **made issue** - Add an additional navigation item at the top labeled “Help” as we will use that page to include basic instructions, examples, etc. Our user base will need this type of support (initial content will be provided). Consider removing the “Home” link at the top since the logo should always link back to home.

- [x] **made issue** - Phone numbers in the museum detail page display as a long string; format as standard 10-digit US phone numbers.

- [x] Remove “Powered by CartoDB” if at all possible.

Functionality/UX:

- [ ] **made issue** Selecting a specific museum will take the user directly to the detail page for museum

- [x] The “Address” column in the results page does not display anything. Alternately, could this column be used for URL? *removed column*

- [x] The “Type” column uses the abbreviations; is it possible to use the legend name? Otherwise, the user has no indication of what the initials mean. Alternately, these initials can be parenthetically added to the end of each legend name.

- [x] For “Revenue” column, if there is no value, is it worthwhile to put “na” or similar? Or is blank preferred?

- [x] The “View” button may be better named as “View & Analyze” or “Analyze” so it’s clear that that where the user can go deeper into analysis. Or Perhaps there’s a better single word.

- [x] When selecting a museum, the “Families in Poverty” chloropleth automatically appears. The screen should start with no chloropleth layers active and the user can select layers to start with.

- [x] When a museum is selected, the pin icon should remain so that the user always knows where the museum is and which museum is selected. The pin goes away when going from the search results page to the museum detail page.

- [x] **deferred** The results page information does not change when the map is zoomed in or out.

- [x] The layers icon, could be more prominent; perhaps including the word “Layers” next to the graphic would help the user know what it is (again, the user base for this tool is not savvy with mapping-related tools).

- [x] When scrolling down on a museum detail page (on 13” MacBook Air) there is a large whitespace between the bottom of the map and the visual display of data. See screen cap below:

- [x] **using email - made issue** “Submit Museum Update” – page content and form fields will be provided.

- [x] **made issue** - Make the custom radius show miles as it is being drawn, rather than km.

- [x] **made issue** - In general, it is vital that there be an easy way for users to see % in addition to (or in same cases, instead of) the full value. In some cases, this can be added to the roll-over box that displays the number. In some cases, this would be best if it were added to the chart (such as with the bar charts for Race and Employment). In most cases, users are more interested in % than actual numbers, so graphs could display % and show the actual number in the roll-over.

- [x] **made issue** - We need to include some basic measure of Hispanic/Latino population, which is not currently on this; it could be a component of the Race chart (relabled as “Race/Ethnicity”) or as a single number/percent.

- [ ] The “NEARBY MUSEUMS” label is still being reviewed in terms of an ideal name. Will review and determine if there is an alternate label selected.

- [x] **made issue** - In the “NEARBY MUSEUMS” charts, the total number should be provided in the heading, such as “Museums in State: ####” as the header. Same applies to “Museums in Selected Area.”

- [x] Switch the order of “Museums in Selected Area” and “Museums in State” to display the specific area first, then to the broader geography.

- [x] In the “Households” tab, the first three data boxes should be Total Households, Median Household Income, Median Home Value (in that order). The next three should be Median Year Moved In, Household Types, Household Languages

- [x] In general, the labels for the data in all three tabs should be consistently written, using a capital letter for the first letter of each word (except for ancillary words like of, in, etc.

- [x]  **deferred** - In “NEARBY MUSEUMS” – We will be providing information on an additional chart and measures that would appear in this section.

- [x] In the footer of the data pages, include the sources, in small text:
“People and Household Data: U.S. Census Bureau, American Community Survey, 2009-2013.”
“Museum Data: Museum Universe Data File, Compiled by IMLS and Drexel University.”

- [x] Change the radius drop down options to 1, 3, and 25 miles to accommodate rural areas.

- [x]  **deferred** - CMS: How will we be able to update the static content on pages such as “About,” “Contact,” “Help,” etc? Is it a WordPress template?

- [x] **made issue - using email** Is it preferable for the contact mechanism to be a contact form vs. email address? If a form is best, a standard form with contact info and comment box should suffice. The form can transmit to nvakharia@drexel.edu, with a subject line of “MuseumStat Contact”

- [x] “3D STREET GALLERY” shows up on a map result in Philadelphia, but has a listed address of Grand Forks, ND – please look into the cause of this

Future Work (short-term):

• In the “Layers” function, allow users to select by museum type.

• Ability to select an entire state and see the analysis.

• Simple ability to share a map and data page.

• Additional point and layer data to include public schools, congressional districts, etc.

**Comment by CloudNiner** [comment]
Can this be closed? The only remaining issue was the Nearby Museums tab name, and that was updated in #102

**Comment by nevillevak** [comment]
Hi – It looks like a couple things have not been completed from this list:

- The Search bar default text has not been updated (also added this the second-round list). It should read “SEARCH BY MUSEUM, CITY, OR ZIP CODE”

- The “Powered by CartoDB” still appeas on the museum detail page.

- The email links for “Submit Museum Update” and “Contact Us” button are not active (info@museumstat.org forwards to museumstat@gmail.com which forwards to me).

- The logo in the upper left does not appear to have been made larger. If it helps to make the three text links to the right of it larger, please do that as well.

These appear to be the only things left on this list. Let me know if you have any questions.

Thanks,
Neville
________________________________
Neville K. Vakharia
Assistant Professor and Research Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, 210H
215-571-4439
nvakharia@drexel.edu

Office Hours:
Tuesdays and Thursdays, 2:00 – 5:00
By appointment only
